/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function5;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.tinkoff.edu.java.scrapper.domain.jooq.Keys;
import ru.tinkoff.edu.java.scrapper.domain.jooq.Public;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records.StackoverflowQuestionsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StackoverflowQuestions extends TableImpl<StackoverflowQuestionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.stackoverflow_questions</code>
     */
    public static final StackoverflowQuestions STACKOVERFLOW_QUESTIONS = new StackoverflowQuestions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StackoverflowQuestionsRecord> getRecordType() {
        return StackoverflowQuestionsRecord.class;
    }

    /**
     * The column <code>public.stackoverflow_questions.id</code>.
     */
    public final TableField<StackoverflowQuestionsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field("gen_random_uuid()", SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.stackoverflow_questions.question_id</code>.
     */
    public final TableField<StackoverflowQuestionsRecord, Long> QUESTION_ID = createField(DSL.name("question_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.stackoverflow_questions.created_at</code>.
     */
    public final TableField<StackoverflowQuestionsRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field("now()", SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.stackoverflow_questions.updated_at</code>.
     */
    public final TableField<StackoverflowQuestionsRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column
     * <code>public.stackoverflow_questions.answers_updated_at</code>.
     */
    public final TableField<StackoverflowQuestionsRecord, OffsetDateTime> ANSWERS_UPDATED_AT = createField(DSL.name("answers_updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field("now()", SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private StackoverflowQuestions(Name alias, Table<StackoverflowQuestionsRecord> aliased) {
        this(alias, aliased, null);
    }

    private StackoverflowQuestions(Name alias, Table<StackoverflowQuestionsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.stackoverflow_questions</code> table
     * reference
     */
    public StackoverflowQuestions(String alias) {
        this(DSL.name(alias), STACKOVERFLOW_QUESTIONS);
    }

    /**
     * Create an aliased <code>public.stackoverflow_questions</code> table
     * reference
     */
    public StackoverflowQuestions(Name alias) {
        this(alias, STACKOVERFLOW_QUESTIONS);
    }

    /**
     * Create a <code>public.stackoverflow_questions</code> table reference
     */
    public StackoverflowQuestions() {
        this(DSL.name("stackoverflow_questions"), null);
    }

    public <O extends Record> StackoverflowQuestions(Table<O> child, ForeignKey<O, StackoverflowQuestionsRecord> key) {
        super(child, key, STACKOVERFLOW_QUESTIONS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<StackoverflowQuestionsRecord> getPrimaryKey() {
        return Keys.STACKOVERFLOW_QUESTIONS_PK;
    }

    @Override
    public List<UniqueKey<StackoverflowQuestionsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UNIQUE_QUESTION_ID);
    }

    @Override
    public StackoverflowQuestions as(String alias) {
        return new StackoverflowQuestions(DSL.name(alias), this);
    }

    @Override
    public StackoverflowQuestions as(Name alias) {
        return new StackoverflowQuestions(alias, this);
    }

    @Override
    public StackoverflowQuestions as(Table<?> alias) {
        return new StackoverflowQuestions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public StackoverflowQuestions rename(String name) {
        return new StackoverflowQuestions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StackoverflowQuestions rename(Name name) {
        return new StackoverflowQuestions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public StackoverflowQuestions rename(Table<?> name) {
        return new StackoverflowQuestions(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<UUID, Long, OffsetDateTime, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super UUID, ? super Long, ? super OffsetDateTime, ? super OffsetDateTime, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function5<? super UUID, ? super Long, ? super OffsetDateTime, ? super OffsetDateTime, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
