/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq.tables;


import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.tinkoff.edu.java.scrapper.domain.jooq.Keys;
import ru.tinkoff.edu.java.scrapper.domain.jooq.Public;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records.TgChatsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TgChats extends TableImpl<TgChatsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.tg_chats</code>
     */
    public static final TgChats TG_CHATS = new TgChats();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TgChatsRecord> getRecordType() {
        return TgChatsRecord.class;
    }

    /**
     * The column <code>public.tg_chats.id</code>.
     */
    public final TableField<TgChatsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field("gen_random_uuid()", SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.tg_chats.chat_id</code>.
     */
    public final TableField<TgChatsRecord, Long> CHAT_ID = createField(DSL.name("chat_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private TgChats(Name alias, Table<TgChatsRecord> aliased) {
        this(alias, aliased, null);
    }

    private TgChats(Name alias, Table<TgChatsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.tg_chats</code> table reference
     */
    public TgChats(String alias) {
        this(DSL.name(alias), TG_CHATS);
    }

    /**
     * Create an aliased <code>public.tg_chats</code> table reference
     */
    public TgChats(Name alias) {
        this(alias, TG_CHATS);
    }

    /**
     * Create a <code>public.tg_chats</code> table reference
     */
    public TgChats() {
        this(DSL.name("tg_chats"), null);
    }

    public <O extends Record> TgChats(Table<O> child, ForeignKey<O, TgChatsRecord> key) {
        super(child, key, TG_CHATS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TgChatsRecord> getPrimaryKey() {
        return Keys.TG_CHATS_PK;
    }

    @Override
    public List<UniqueKey<TgChatsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UNIQUE_CHAT_ID);
    }

    @Override
    public TgChats as(String alias) {
        return new TgChats(DSL.name(alias), this);
    }

    @Override
    public TgChats as(Name alias) {
        return new TgChats(alias, this);
    }

    @Override
    public TgChats as(Table<?> alias) {
        return new TgChats(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TgChats rename(String name) {
        return new TgChats(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TgChats rename(Name name) {
        return new TgChats(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TgChats rename(Table<?> name) {
        return new TgChats(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super UUID, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super UUID, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
