version: "3.9"
services:
  bot:
    build:
      dockerfile: bot/Dockerfile
      context: .
    depends_on:
      - scrapper
  scrapper:
    build:
      dockerfile: scrapper/Dockerfile
      context: .
