#file: noinspection SpringBootApplicationYaml
app:
  error_description:
    api: Некорректные параметры запроса
    server: Ошибка сервера
    tg_chat_not_found: Вы не зарегистрированы. Зарегистрируйтесь с помощью команды /start
    tg_chat_exists: Вы уже зарегистрированы
    stackoverflow_question_not_found: Вопроса на Stack Overflow не существует
    github_repository_not_found: GitHub репозитория не существует
    link_not_found: Ссылка не найдена
    link_not_supported: Ссылка не поддерживается
    link_exists: Ссылка уже добавлена
  web_client:
    github:
      base_url: https://api.github.com
      api_version: 2022-11-28
    stack_exchange:
      base_url: https://api.stackexchange.com
      api_version: 2.3
    bot_base_url: http://localhost:8080
  scheduler:
    interval: 1h
    batch_size: 100
  database:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
  rabbit_mq:
    exchange_name: scrapper_bot_exchange
    queue_name: updates_queue
  database-access-type: jpa
  use_queue: true
server:
  port: 8081
spring:
  liquibase:
    enabled: false
  devtools:
    livereload:
      port: 35730
springdoc:
  swagger-ui:
    path: /swagger-ui
