#file: noinspection SpringBootApplicationYaml
app:
  error_description:
    api: Некорректные параметры запроса
    server: Ошибка сервера
    tg_chat_not_found: Чат не существует
  web_client:
    github:
      base_url: https://api.github.com/
      api_version: 2022-11-28
    stack_exchange:
      base_url: https://api.stackexchange.com/
      api_version: 2.3
placeholder:
  link_response: &link_response
    id: 1
    url: https://github.com/sanyarnd/tinkoff-java-course-2022
  list_links_response:
    links:
      - *link_response
    size: 1
server:
  port: 8080
spring:
  devtools:
    livereload:
      port: 35730
springdoc:
  swagger-ui:
    path: /swagger-ui
