/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq;


import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Databasechangelog;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Databasechangeloglock;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.GithubRepositories;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Links;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.StackoverflowQuestions;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.TgChats;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.github_repositories</code>.
     */
    public static final GithubRepositories GITHUB_REPOSITORIES = GithubRepositories.GITHUB_REPOSITORIES;

    /**
     * The table <code>public.links</code>.
     */
    public static final Links LINKS = Links.LINKS;

    /**
     * The table <code>public.stackoverflow_questions</code>.
     */
    public static final StackoverflowQuestions STACKOVERFLOW_QUESTIONS = StackoverflowQuestions.STACKOVERFLOW_QUESTIONS;

    /**
     * The table <code>public.tg_chats</code>.
     */
    public static final TgChats TG_CHATS = TgChats.TG_CHATS;
}
