name: Scrapper Java CI

on:
  push:
    paths:
      - scrapper/migrations/**
      - scrapper/src/**
      - .github/workflows/scrapper.yml

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgresql:
        image: postgres:15
        env:
          POSTGRES_DB: scrapper
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Run migrations
        uses: liquibase/liquibase-github-action@v7
        with:
          operation: 'update'
          classpath: 'scrapper/migrations'
          changeLogFile: 'master.yml'
          username: postgres
          password: postgres
          url: jdbc:postgresql://postgresql:5432/scrapper
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn package -pl scrapper -am
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: scrapper/
          push: false
